version: '2.0'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: rabbitmq
    volumes:
      - './.data:/var/lib/rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - 'RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}'
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}'
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}'
      - 'RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}'
    networks:
      - crawlolx
  servicewa:
    hostname: servicewa
    build:
      context: .
      dockerfile:  serviceSendTextMessage/Dockerfile
    volumes:
      - './.data/WhatsAppSession:/tmp/WhatsAppSession'
    networks:
      - crawlolx
    tty: true
    command: "/code/serviceSendTextMessage/serviceSendTextMessage"
  serivicecrawl:
    hostname: serivicecrawl
    build:
      context: .
      dockerfile: crawl-olx/Dockerfile
    networks:
      - crawlolx
    tty: true
    command: "crond -l 2 -f"
volumes:
  devshm: null
networks:
  crawlolx: null
