version: '2.0'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: rabbitmq
    volumes:
      - './mnesia1:/var/lib/rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - 'RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}'
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}'
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}'
      - 'RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}'
    networks:
      - crawlolx
  servicewa:
    hostname: servicewa
    build: .
    networks:
      - crawlolx
    command: "/code/serviceSendTextMessage/serviceSendTextMessage"
    tty: true
volumes:
  devshm: null
networks:
  crawlolx: null
